// This file is auto-generated by @hey-api/openapi-ts

/**
 * Action
 * An authenticated action
 */
export type Action = {
    /**
     * Additional data associated with the action
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * The unique identifier for the action
     */
    id: string;
    /**
     * The timestamp when the action was created
     */
    inserted_at: string;
    /**
     * The current state of the action
     */
    state: 'allow' | 'timeout' | 'block' | 'pending';
    /**
     * The timestamp when the action was last updated
     */
    updated_at: string;
};

export type PasswordlessApiActionControllerAuthenticateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/server/v1/actions/authenticate';
};

export type PasswordlessApiActionControllerAuthenticateErrors = {
    /**
     * Unauthorised
     */
    401: {
        [key: string]: unknown;
    };
};

export type PasswordlessApiActionControllerAuthenticateError = PasswordlessApiActionControllerAuthenticateErrors[keyof PasswordlessApiActionControllerAuthenticateErrors];

export type PasswordlessApiActionControllerAuthenticateResponses = {
    /**
     * Action
     */
    200: Action;
};

export type PasswordlessApiActionControllerAuthenticateResponse = PasswordlessApiActionControllerAuthenticateResponses[keyof PasswordlessApiActionControllerAuthenticateResponses];

export type PostApiServerV1ActionsQueryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/server/v1/actions/query';
};

export type PasswordlessApiActionControllerShowData = {
    body?: never;
    path: {
        /**
         * Action ID
         */
        id: string;
    };
    query?: never;
    url: '/api/server/v1/actions/{id}';
};

export type PasswordlessApiActionControllerShowErrors = {
    /**
     * Unauthorised
     */
    401: {
        [key: string]: unknown;
    };
};

export type PasswordlessApiActionControllerShowError = PasswordlessApiActionControllerShowErrors[keyof PasswordlessApiActionControllerShowErrors];

export type PasswordlessApiActionControllerShowResponses = {
    /**
     * Action
     */
    200: Action;
};

export type PasswordlessApiActionControllerShowResponse = PasswordlessApiActionControllerShowResponses[keyof PasswordlessApiActionControllerShowResponses];

export type GetApiServerV1AppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/server/v1/app';
};

export type GetApiServerV1AppAuthenticatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/server/v1/app/authenticators';
};

export type GetApiServerV1UsersByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/server/v1/users/{id}';
};

export type ClientOptions = {
    baseUrl: 'https://eu.passwordless.tools' | (string & {});
};