[package]
name = "passwordless_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "passwordless_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
rustler = "0.34.0"
rand_distr = "0.4.3"
plotters = "0.3.7"