[package]
name = "passwordless_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "passwordless_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
mrml = { version = "5.0.0", default-features = false, features = ["parse", "render"] }
rustler = "0.36.1"