baseURL = 'https://passwordless.tools/'
languageCode = 'en-us'
title = 'Passwordless Tools'
theme = 'ananke'
enableRobotsTXT = true

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepComments = false
      keepWhitespace = false

[outputs]
  home = ["HTML", "RSS", "JSON"]