import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :passwordless, PasswordlessWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  static_url: [scheme: "https", host: "cdn.eu.passwordless.tools", port: 443]

# Configures Swoosh
config :passwordless, Passwordless.Mailer, adapter: Swoosh.Adapters.ExAwsAmazonSES

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Passwordless.Finch.Swoosh

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Configures the cache to ElastiCache
config :passwordless, :cache, adapter: Passwordless.Cache.Redis

# Configures the object storage to AWS
config :passwordless, :storage, adapter: Passwordless.Storage.Amazon

# Configures the rate limit
config :passwordless, :rate_limit, adapter: Passwordless.RateLimit.Redis

# Configures the secret manager to AWS
config :passwordless, :secret_manager,
  adapter: Passwordless.SecretManager.Amazon,
  secret_name: "arn:aws:secretsmanager:eu-west-1:728247919352:secret:general-application-config-uL5n4J"

# Configures the media uploader to S3
config :passwordless, :file_uploads, adapter: Passwordless.FileUploads.S3

# Configures AWS
config :ex_aws, require_imds_v2: true

# Configure Sentry
config :sentry,
  dsn: "https://eaf9d36da5cae6187b69cca1312497e3@o4507273188802560.ingest.de.sentry.io/4508026525450320",
  client: Passwordless.SentryClient,
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Only print warning messages in production
config :logger, :console,
  level: :warning,
  compile_time_purge_level: :info

# Configure session
config :passwordless, :session,
  secure: true,
  domain: "eu.passwordless.tools",
  same_site: "None"

# Configure CORS
config :passwordless, :cors,
  origins: [
    ~r{^https?://(.*\.)?passwordless\.tools$},
    ~r{^https?://(.*\.)?passwordlesstools\.com$}
  ]

# Configure the environment
config :passwordless, :env, :prod
