// This file is auto-generated by @hey-api/openapi-ts

/**
 * ActionTemplate
 * An template for a action-based authentication flow
 */
export type ActionTemplate = {
    /**
     * The unique identifier for the action
     */
    id: string;
    /**
     * The timestamp when the action was created
     */
    inserted_at: string;
    /**
     * The timestamp when the action was last updated
     */
    updated_at: string;
};

/**
 * App
 * A passwordless application tenant
 */
export type App = {
    /**
     * The unique identifier for the action
     */
    id: string;
    /**
     * The timestamp when the app was created
     */
    inserted_at: string;
    /**
     * The name of the application
     */
    name: string;
    /**
     * The current state of the app
     */
    state: 'active' | 'suspended';
    /**
     * The timestamp when the app was last updated
     */
    updated_at: string;
};

export type PasswordlessApiActionTemplateControllerShowData = {
    body?: never;
    path: {
        /**
         * Action Template ID
         */
        id: string;
    };
    query?: never;
    url: '/api/client/v1/action-templates/{id}';
};

export type PasswordlessApiActionTemplateControllerShowErrors = {
    /**
     * Unauthorised
     */
    401: {
        [key: string]: unknown;
    };
};

export type PasswordlessApiActionTemplateControllerShowError = PasswordlessApiActionTemplateControllerShowErrors[keyof PasswordlessApiActionTemplateControllerShowErrors];

export type PasswordlessApiActionTemplateControllerShowResponses = {
    /**
     * ActionTemplate
     */
    200: ActionTemplate;
};

export type PasswordlessApiActionTemplateControllerShowResponse = PasswordlessApiActionTemplateControllerShowResponses[keyof PasswordlessApiActionTemplateControllerShowResponses];

export type PasswordlessApiAppClientControllerIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/client/v1/app';
};

export type PasswordlessApiAppClientControllerIndexErrors = {
    /**
     * Unauthorised
     */
    401: {
        [key: string]: unknown;
    };
};

export type PasswordlessApiAppClientControllerIndexError = PasswordlessApiAppClientControllerIndexErrors[keyof PasswordlessApiAppClientControllerIndexErrors];

export type PasswordlessApiAppClientControllerIndexResponses = {
    /**
     * App
     */
    200: App;
};

export type PasswordlessApiAppClientControllerIndexResponse = PasswordlessApiAppClientControllerIndexResponses[keyof PasswordlessApiAppClientControllerIndexResponses];

export type ClientOptions = {
    baseUrl: 'https://eu.passwordless.tools' | (string & {});
};